In [5]:
import sklearn
import numpy as np
import scipy
print(sklearn.__version__)
print(numpy.version.version)
print(scipy.__version__)

0.23.2
1.19.2
1.5.2


# Classifying Iris

In [24]:
# using the pre-built dataset
from sklearn import datasets
iris = datasets.load_iris()
print(iris.feature_names)
print(iris.data)
print(iris.target)
print(iris.target_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3

In [17]:
# CREATE training set and test set
from sklearn.model_selection import train_test_split
# data value
x = iris.data
# data label
y = iris.target
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4)

In [25]:
# TRAIN classifier (estimator = nb of trees, random_state = randomess of bootstrapping) )
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=10, random_state=123456)
rf = rf.fit(x_train, y_train)
# rf is the classifier model. Depending on the iris size, finds out
# which flower it is (0, 1 or 2 == iris.target_names)

In [26]:
# TEST model: predict() gives the prediction results of the test set using 
# the previously trained 'rf' model. Then accuracy is tested with it's 
# corresponding label test set.
from sklearn.metrics import accuracy_score
predicted = rf.predict(x_test)
print(predicted)
accuracy = accuracy_score(y_test, predicted)
print(f'Mean acc score: {accuracy: .3}')

[1 0 1 0 0 0 2 1 0 0 0 1 0 2 1 2 2 0 1 1 2 0 0 0 1 1 1 1 1 2 0 0 1 2 0 0 0
 0 1 2 0 2 1 1 2 0 0 2 0 1 1 0 2 1 1 1 2 2 2 0]
Mean acc score:  0.95


In [28]:
# Using K-fold split data into multiple training and validation sets.
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
for train, test in kf.split(x):
    print("%s %s" % (train, test))

[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101 102 103
 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121
 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139
 140 141 142 143 144 145 146 147 148 149] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49 100 101 102 103
 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121
 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139
 140 141 142 143 144 145 146 147 148 149] [50 51 52 53 54 55 56 57 58 59 6

# Second classification

In [36]:
from io import StringIO
path = "scikit-test-files"

# create training sets
X_train = np.loadtxt(StringIO(open(f"{path}/train/X_train.txt", "r").read()))
y_train = np.loadtxt(StringIO(open(f"{path}/train/y_train.txt", "r").read()))
X_test = np.loadtxt(StringIO(open(f"{path}/test/X_test.txt", "r").read()))
y_test = np.loadtxt(StringIO(open(f"{path}/test/y_test.txt", "r").read()))

# train model
rf = RandomForestClassifier(n_estimators=10, random_state=123456)
rf = rf.fit(X_train, y_train)

# predict results
predicted = rf.predict(X_test)
accuracy = accuracy_score(y_test, predicted)
print(f"The accuracy of this model is:{accuracy: .3}%")

The accuracy of this model is: 0.911%
